Repository adoptium/aqa-tests, pull requests merged in 2018-11, with the labels that each got.

#666 Update
  openjdk_regression/ProblemList_openjdk11-openj9.txt
Labels: bug

#667 Update
  openjdk_regression/ProblemList_openjdk11-openj9.txt
Labels: bug

#673 Include back Mauve load tests in SE80 build after omitting CORBA Tests
  systemtest/playlist.xml
Labels: bug

#668 Update
  openjdk_regression/ProblemList_openjdk11-openj9.txt
Labels: bug

#672 Update
  openjdk_regression/ProblemList_openjdk11-openj9.txt
Labels: bug

#670 Add Queue stage to test pipelines
  buildenv/jenkins/openjdk_aarch64_linux
  buildenv/jenkins/openjdk_ppc64_aix
  buildenv/jenkins/openjdk_ppc64le_linux
  buildenv/jenkins/openjdk_s390x_linux
  buildenv/jenkins/openjdk_s390x_zos
  buildenv/jenkins/openjdk_x86-64_linux
  buildenv/jenkins/openjdk_x86-64_linux_docker
  buildenv/jenkins/openjdk_x86-64_linux_largeHeap
  buildenv/jenkins/openjdk_x86-64_macos
  buildenv/jenkins/openjdk_x86-64_osx
  buildenv/jenkins/openjdk_x86-64_osx_largeHeap
  buildenv/jenkins/openjdk_x86-64_windows
Labels: enhancement

#676 Update label ppc to ppc64
  buildenv/jenkins/openjdk_ppc64_aix
Labels: enhancement

#685 Update node label combination for docker enabled linux machines
  buildenv/jenkins/openjdk_x86-64_linux_docker
Labels: bug

#683 Update get.sh for OSX
  get.sh
Labels: bug, enhancement

#681 Update JDK11 jdk test groups
  openjdk_regression/playlist.xml
Labels: bug, type:openjdk

#682 Use pre-built mauve.jar in systemtest builds
  buildenv/jenkins/JenkinsfileBase
  systemtest/build.xml
Labels: enhancement

#688 Add missing flag to the invocation of openj9-systemtest build
  systemtest/build.xml
Labels: bug

#691 Add docker prune --all at the beginning of docker based test execution
  thirdparty_containers/build.xml
Labels: enhancement

#690 Add jenkinsfile for getDependency build
  buildenv/jenkins/getDependency
Labels: enhancement

#692 Change git URL prefix to https to support ci.eclipse jenkins
  buildenv/jenkins/getDependency
Labels: bug

#694 Support release tag in openjdk regression test
  buildenv/jenkins/JenkinsfileBase
  openjdk_regression/build.xml
Labels: enhancement

#696 Rewmove isAutomated flag from systemtest build file
  buildenv/jenkins/JenkinsfileBase
  systemtest/build.xml
Labels: bug

#704 Skip regression jre tests
  openjdk_regression/playlist.xml
Labels: bug

#702 enhance get.sh
  doc/userGuide.md
  get.sh
Labels: enhancement

#703 Include back modularity tests to jdk11 build
  systemtest/playlist.xml
Labels: bug

#705 Update <subset> with numeric value
  jck/runtime.api/playlist.xml
  jck/runtime.lang/playlist.xml
  jck/runtime.vm/playlist.xml
  openjdk_regression/playlist.xml
  performance/idle_micro/playlist.xml
  performance/odm/playlist.xml
  thirdparty_containers/example-test/playlist.xml
  thirdparty_containers/lucene-solr/playlist.xml
Labels: enhancement

#708 Temporarily exclude security enabled JLM tests on Windows
  systemtest/playlist.xml
Labels: bug

#709 Fixed spelling of <disabled> tag
  systemtest/playlist.xml
Labels: bug

#710 Temporarily exclude ExplicitModulesTest
  systemtest/playlist.xml
Labels: bug

#707 Add systemtest.mk file to include changes to enable testing on cygwin
  systemtest/playlist.xml
  systemtest/systemtest.mk
Labels: bug

#718 Adding missing bracket
  buildenv/jenkins/openjdk_aarch64_linux
Labels: bug

#716 Temporarily exclude PatchModule*Test_PlatformModPatchModule on AIX
  systemtest/playlist.xml
Labels: bug
