Repository adoptium/aqa-tests, pull requests merged in 2018-04, with the labels that each got.

#362 Support test integration into parent pipelines
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#357 update jck build xml to use platform info
  jck/build.xml
Labels: enhancement, type:jck

#361 Re-enable java/lang/System/Versions.java
  openjdk_regression/ProblemList_openjdk8-openj9.txt
  openjdk_regression/ProblemList_openjdk9-openj9.txt
Labels: bug

#358 Remove duplicate parameters in personal build jenkins
  buildenv/jenkins/Jenkinsfile_personal
Labels: enhancement

#374 Correct copyright to Apache 2.0 license header.
  thirdparty_containers/example-test/dockerfile/Dockerfile
  thirdparty_containers/example-test/dockerfile/example-test.sh
  thirdparty_containers/scala/dockerfile/Dockerfile
  thirdparty_containers/scala/dockerfile/scala-test.sh
  thirdparty_containers/tomcat/dockerfile/Dockerfile
  thirdparty_containers/tomcat/dockerfile/tomcat-test.sh
Labels: enhancement

#377 Remove upstream sdk choice in personal build
  buildenv/jenkins/Jenkinsfile_personal
Labels: enhancement

#378 set outputTapToConsole to false in TapPublisher
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#373 Update test doc
  README.md
  doc/ciPipeline.jpg
  doc/jenkinsParameters.jpg
  doc/overviewDiagram.md
  doc/overviewOfAdoptTests.svg
  doc/pipelineFromSCM.jpg
  doc/userGuide.md
Labels: docs

#381 Re-enable tests under issues 125 which are not reproducible
  openjdk_regression/ProblemList_openjdk8.txt
Labels: enhancement

#369 Add Jenkins testsuite to open source packages testing
  thirdparty_containers/jenkins/build.xml
  thirdparty_containers/jenkins/dockerfile/Dockerfile
  thirdparty_containers/jenkins/dockerfile/jenkins-test.sh
  thirdparty_containers/jenkins/playlist.xml
Labels: enhancement

#368 Update JCK readme to describe JCK execution in docker
  jck/README.md
Labels: enhancement

#397 Remove duplicate subset jdk_sound
  openjdk_regression/playlist.xml
Labels: bug

#395 update jck playlist to add JCK10 specific test buckets
  buildenv/docker/Dockerfile
  buildenv/docker/README.md
  jck/runtime.api/playlist.xml
  jck/runtime.vm/playlist.xml
Labels: enhancement

#394 enable functional and system test in OpenJ9 Jenkins
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/Jenkinsfile_personal
  buildenv/jenkins/openjdk10_aarch64_linux
  buildenv/jenkins/openjdk10_ppc64_aix
  buildenv/jenkins/openjdk10_ppc64le_linux
  buildenv/jenkins/openjdk10_s390x_linux
  buildenv/jenkins/openjdk10_x86-64_linux
  buildenv/jenkins/openjdk10_x86-64_macos
  buildenv/jenkins/openjdk8_aarch64_linux
  buildenv/jenkins/openjdk8_ppc64_aix
  buildenv/jenkins/openjdk8_ppc64le_linux
  buildenv/jenkins/openjdk8_s390x_linux
  buildenv/jenkins/openjdk8_x86-64_linux
  buildenv/jenkins/openjdk8_x86-64_macos
  buildenv/jenkins/openjdk9_aarch64_linux
  buildenv/jenkins/openjdk9_ppc64_aix
  buildenv/jenkins/openjdk9_ppc64le_linux
  buildenv/jenkins/openjdk9_s390x_linux
  buildenv/jenkins/openjdk9_x86-64_linux
  buildenv/jenkins/openjdk9_x86-64_macos
  example/.gitignore
  example/build.xml
  example/playlist.xml
  example/src/net/adoptopenjdk/test/example/ImportantTest.java
  example/src/net/adoptopenjdk/test/example/SimpleTest.java
  example/testng.xml
  functional/build.xml
  get.sh
  utils/src/net/adoptopenjdk/test/util/ExcludeData.java
  utils/src/net/adoptopenjdk/test/util/IncludeExcludeTestAnnotationTransformer.java
Labels: enhancement

#392 Add Lucene-Solr standard test suite to External Tests
  thirdparty_containers/example-test/dockerfile/Dockerfile
  thirdparty_containers/lucene-solr/build.xml
  thirdparty_containers/lucene-solr/dockerfile/Dockerfile
  thirdparty_containers/lucene-solr/dockerfile/lucene-solr-test.sh
  thirdparty_containers/lucene-solr/playlist.xml
Labels: enhancement

#399 add a quick example to JCK readme file
  jck/README.md
Labels: enhancement

#401 update jck readme to confirm the jck_root structure
  jck/README.md
Labels: docs, enhancement
