Repository adoptium/aqa-tests, pull requests merged in 2018-09, with the labels that each got.

#533 Add Thorntail (WildFly-Swarm) MicroProfile TCK tests to build
  thirdparty_containers/thorntail-mp-tck/build.xml
  thirdparty_containers/thorntail-mp-tck/dockerfile/Dockerfile
  thirdparty_containers/thorntail-mp-tck/dockerfile/thorntail-mp-tck.sh
  thirdparty_containers/thorntail-mp-tck/playlist.xml
Labels: enhancement

#537 Add docker cp step to copy jenkins test result xmls to host for reporting
  thirdparty_containers/jenkins/playlist.xml
Labels: bug

#539 Add more tests to jck sanity
  jck/runtime.lang/playlist.xml
  jck/runtime.vm/playlist.xml
Labels: enhancement

#540 Enable system tests for JDK11
  systemtest/playlist.xml
Labels: enhancement

#541 Add ability to download multiple files from a customized url
  get.sh
Labels: enhancement

#545 Run the regular external tests as sanity and mp tck as extended
  thirdparty_containers/derby/playlist.xml
  thirdparty_containers/elasticsearch/playlist.xml
  thirdparty_containers/example-test/playlist.xml
  thirdparty_containers/jenkins/playlist.xml
  thirdparty_containers/kafka/playlist.xml
  thirdparty_containers/lucene-solr/playlist.xml
  thirdparty_containers/scala/playlist.xml
  thirdparty_containers/tomcat/playlist.xml
  thirdparty_containers/wildfly/playlist.xml
Labels: enhancement

#542 Support untarring native test libs gz
  get.sh
Labels: enhancement

#550 Add README for systemtest
  systemtest/README.md
Labels: enhancement

#552 Add OpenLiberty MicroProfile TCK to external test
  thirdparty_containers/openliberty-mp-tck/build.xml
  thirdparty_containers/openliberty-mp-tck/dockerfile/Dockerfile
  thirdparty_containers/openliberty-mp-tck/dockerfile/openliberty-mp-tck.sh
  thirdparty_containers/openliberty-mp-tck/playlist.xml
Labels: enhancement

#555 Update the CI links in the readme document
  README.md
Labels: docs

#559 Build local release of open-liberty + switch to running metrics tck 1.1
  thirdparty_containers/openliberty-mp-tck/dockerfile/openliberty-mp-tck.sh
  thirdparty_containers/openliberty-mp-tck/playlist.xml
Labels: bug

#572 Change the condition order
  get.sh
Labels: bug

#576 Update JAVA_IMPL to JDK_IMPL
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/Jenkinsfile_personal
Labels: bug

#568 Update hotspot jtreg test
  openjdk_regression/openjdk_regression.mk
  openjdk_regression/playlist.xml
Labels: enhancement

#567 Always Clean Workspace after build
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#590 Exclude bigdecimal math load test form jdk11
  systemtest/playlist.xml
Labels: bug

#591 Add support to upload test output to artifactory
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#595 Exclude problematic tests
  openjdk_regression/ProblemList_openjdk11-openj9.txt
  openjdk_regression/ProblemList_openjdk11.txt
Labels: bug

#598 exclude update
  openjdk_regression/ProblemList_openjdk11.txt
Labels: bug

#603 Add another perm fail
  openjdk_regression/ProblemList_openjdk11-openj9.txt
Labels: bug

#604 Exclude system tests failing on aarch64
  systemtest/playlist.xml
Labels: bug

#584 Support for jitaas testing
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement
