Repository adoptium/aqa-tests, pull requests merged in 2019-08, with the labels that each got.

#1240 remove name('AdoptOpenJDK') in testJobTemplate
  buildenv/jenkins/testJobTemplate
Labels: bug

#1257 Fixed openjdk download when jdk_version is next
  buildenv/jenkins/JenkinsfileBase
  openjdk/build.xml
Labels: bug

#1214 Move compilation of JCK to openjdk.test.jck/build.xml + fix Git update step if jck materials exists on disc
  buildenv/jenkins/JenkinsfileBase
  jck/build.xml
  jck/jck.mk
  jck/runtime.api/playlist.xml
  jck/runtime.lang/playlist.xml
  jck/runtime.vm/playlist.xml
  jck/runtime.xml_schema/playlist.xml
Labels: bug

#1256 Enhancement when customize target is empty
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#1263 Set umask 0002 on macos for shared classes caches to work
  systemtest/sharedClasses/playlist.xml
Labels: bug, enhancement

#1274 Exclude failure test on windows with jdk11,13 hs|openj9
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk11.txt
  openjdk/ProblemList_openjdk13-openj9.txt
  openjdk/ProblemList_openjdk13.txt
Labels: bug

#1264 Removed support for JAVA_VERSION variable
  buildenv/jenkins/JenkinsfileBase
  functional/MBCS_Tests/CLDR_11/build.xml
  functional/MBCS_Tests/Compiler/build.xml
  functional/MBCS_Tests/IDN/build.xml
  functional/MBCS_Tests/StAX/build.xml
  functional/MBCS_Tests/annotation/build.xml
  functional/MBCS_Tests/charsets/build.xml
  functional/MBCS_Tests/codepage/build.xml
  functional/MBCS_Tests/codepoint/build.xml
  functional/MBCS_Tests/coin/build.xml
  functional/MBCS_Tests/datetime/build.xml
  functional/MBCS_Tests/env/build.xml
  functional/MBCS_Tests/file/build.xml
  functional/MBCS_Tests/formatter/build.xml
  functional/MBCS_Tests/i18n/build.xml
  functional/MBCS_Tests/jaxp14/build.xml
  functional/MBCS_Tests/jdbc41/build.xml
  functional/MBCS_Tests/locale_matching/build.xml
  functional/MBCS_Tests/nio/build.xml
  functional/MBCS_Tests/pref/build.xml
  functional/MBCS_Tests/regex/build.xml
  functional/MBCS_Tests/scanner/build.xml
  functional/MBCS_Tests/unicode/build.xml
  functional/MBCS_Tests/urlclassloader/build.xml
Labels: bug

#1281 Use regular expression that works on older bash to detect platform
  systemtest/sharedClasses/playlist.xml
Labels: bug

#1283 Fixed SyntheticGCWorkload test
  functional/SyntheticGCWorkload/playlist.xml
Labels: bug

#1287 Removed quiet option from git fetch
  get.sh
Labels: bug

#1275 Exclude tests failures for jdk13 openj9
  openjdk/ProblemList_openjdk13-openj9.txt
Labels: bug

#1254 Updating ProblemList_openjdk11-openj9
  openjdk/ProblemList_openjdk11-openj9.txt
Labels: bug

#1286 Exclude JBS recorded tests
  openjdk/ProblemList_openjdk11.txt
  openjdk/ProblemList_openjdk13.txt
  openjdk/ProblemList_openjdk8.txt
Labels: enhancement

#1290 Problem Lists JDK13 openj9 exclusions
  openjdk/ProblemList_openjdk13-openj9.txt
Labels: bug

#1245 Adding the ability to repeat payloads for the sessions workload
  functional/SyntheticGCWorkload/README.md
  functional/SyntheticGCWorkload/config/config_repetitionDelayExample.xml
  functional/SyntheticGCWorkload/config/config_repetitionDelayExample2.xml
  functional/SyntheticGCWorkload/src/net/adoptopenjdk/casa/workload_sessions/PayloadBuilderSet.java
  functional/SyntheticGCWorkload/src/net/adoptopenjdk/casa/workload_sessions/Workload.java
  functional/SyntheticGCWorkload/src/net/adoptopenjdk/casa/workload_sessions/Workloads.java
  functional/SyntheticGCWorkload/src/net/adoptopenjdk/casa/workload_sessions/configuration/Configuration.java
  functional/SyntheticGCWorkload/src/net/adoptopenjdk/casa/workload_sessions/configuration/PayloadSetConfiguration.java
  functional/SyntheticGCWorkload/src/net/adoptopenjdk/casa/workload_sessions/configuration/WorkloadConfiguration.java
Labels: enhancement

#1309 Set umask 007 for SharedClassesAPI test for all platforms other than Windows
  system/sharedClasses/playlist.xml
Labels: bug

#1311 Add Jenkins Pipeline for Aarch64 Linux LargeHeap
  buildenv/jenkins/openjdk_aarch64_linux_xl
Labels: enhancement
