Repository adoptium/aqa-tests, pull requests merged in 2019-09, with the labels that each got.

#1302 Enabled CS tests on Power
  system/daaLoadTest/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/otherLoadTest/playlist.xml
Labels: enhancement

#1301 Excluding tests from the JDK13 problem lists
  openjdk/ProblemList_openjdk13-openj9.txt
Labels: bug

#1253 Updated problem list for jdk11 openj9 to include links to relevant issues
  openjdk/ProblemList_openjdk11-openj9.txt
Labels: bug

#1324 Enable CS test cases on Power
  system/daaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
Labels: enhancement

#1317 Initiated default values for generic Grinder use
  buildenv/jenkins/JenkinsfileBase
Labels: bug

#1329 Remove -p option from umask as it doesn't work on AIX
  system/sharedClasses/playlist.xml
Labels: bug

#1310 Update JDK11-openj9 Problem List with links to relevant issues
  openjdk/ProblemList_openjdk11-openj9.txt
Labels: bug

#1327 Add option -nativelib with nativelibs available
  buildenv/jenkins/JenkinsfileBase
  get.sh
  openjdk/openjdk.mk
  openjdk/playlist.xml
Labels: enhancement

#1338 Disable -Xint modes from system test
  system/daaLoadTest/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/otherLoadTest/playlist.xml
Labels: enhancement

#1358 Bring tests exclusions over mirroring openj9 exclusions to hotspot
  openjdk/ProblemList_openjdk13.txt
Labels: bug

#1346 Enable compiler api/lang test suites for JCK 11+
  jck/runtime.api/playlist.xml
  jck/runtime.lang/playlist.xml
Labels: enhancement

#1343 Updated links to issues
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk8-openj9.txt
Labels: bug

#1351 Fix compilation failures for Perf Testing
  perf/dacapo/build.xml
  perf/liberty/build.xml
  perf/liberty/configs/benchmark.sh
  perf/liberty/scripts/bin/common_utils.sh
  perf/renaissance/build.xml
Labels: enhancement

#1350 Re-include j.c.util.ArrayBlockingQueue/WhiteBox
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
Labels: bug

#1335 Added documentation to show how to export environment variables
  doc/diagrams/bottom.jpg
  doc/diagrams/branch.jpg
  doc/diagrams/build.jpg
  doc/diagrams/buildListTarget.jpg
  doc/diagrams/commandSection.jpg
  doc/diagrams/export.jpg
  doc/diagrams/openGrinders.jpg
  doc/diagrams/openj9Branch.jpg
  doc/diagrams/openj9Repo.jpg
  doc/diagrams/otherExport.jpg
  doc/diagrams/playListFile.jpg
  doc/diagrams/repo.jpg
  doc/diagrams/resrootLine.jpg
  doc/diagrams/systemFolder.jpg
  doc/diagrams/systemtest.jpg
  doc/diagrams/testCaseName.jpg
  doc/diagrams/testConfig.jpg
  doc/diagrams/testEnv.jpg
  doc/diagrams/testFolder.jpg
  doc/userGuide.md
Labels: docs, enhancement

#1363 Add Grinder link in job description
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#1364 Updating JDK11-openj9 and JDK13-openj9 Problem Lists
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
Labels: bug

#1360 Enhance jdk_custom to also support hotspot and langtools tests
  buildenv/jenkins/JenkinsfileBase
  openjdk/openjdk.mk
  openjdk/playlist.xml
Labels: enhancement

#1361 Limit -nativepath option to test groups needed.
  openjdk/playlist.xml
Labels: enhancement

#1362 Support running openj9 functional native in AdoptOpenJDK
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#1348 Triage/Excluding tests
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
  openjdk/ProblemList_openjdk8-openj9.txt
Labels: bug

#1367 Enable grinder tests with different jdk|impl|platform.
  buildenv/jenkins/JobTemplate.groovy
  buildenv/jenkins/testpipeline.groovy
Labels: enhancement

#1369 JTReg/Nightly Triage
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
  openjdk/ProblemList_openjdk8-openj9.txt
Labels: bug

#1325 Portable interpreter invocation
  functional/SyntheticGCWorkload/concurrent_slack_sweep.sh
  functional/SyntheticGCWorkload/run_abort_test.sh
  functional/SyntheticGCWorkload/run_test.sh
  functional/SyntheticGCWorkload/run_tests.sh
  get.sh
  maketest.sh
  perf/idle_micro/log_parse.sh
  perf/idle_micro/runIdleTest.sh
  perf/liberty/configs/benchmark.sh
  perf/liberty/scripts/bin/common_utils.sh
  perf/liberty/scripts/bin/database_utils.sh
  perf/liberty/scripts/bin/sufp_benchmark.sh
Labels: bug

#1375 Update Rerun in Grinder link
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#1376 Reintroducing tests excluded for openj9 bugs 6671 and 6778
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
Labels: bug
