Repository adoptium/aqa-tests, pull requests merged in 2019-10, with the labels that each got.

#1380 Add BumbleBench
  perf/bumbleBench/build.xml
  perf/bumbleBench/playlist.xml
Labels: enhancement, type:perf

#1383 Triage
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
Labels: bug

#1389 Remove block to re-download openjdk-test repo for developer branch
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#1398 skip remaining ipv6 tests on macOS and skip TestZoneInfo310.java on all
  openjdk/ProblemList_openjdk8.txt
Labels: bug

#1403 Set correct test repo for aarch64 builds
  buildenv/jenkins/openjdk_aarch64_linux
  openjdk/build.xml
Labels: bug

#1404 Fix git repo for jdk8 aarch64
  buildenv/jenkins/openjdk_aarch64_linux
  openjdk/build.xml
Labels: bug

#1414 Add Jenkins files for Linux s390
  buildenv/jenkins/openjdk_s390_linux
  buildenv/jenkins/openjdk_s390x_linux_xl
Labels: enhancement

#1418 Update getDependencies.pl path
  buildenv/jenkins/getDependency
Labels: bug

#1412 Updated JDK8/13-openj9 Problem List
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
  openjdk/ProblemList_openjdk8-openj9.txt
Labels: bug
