Repository adoptium/aqa-tests, pull requests merged in 2019-04, with the labels that each got.

#1053 Exclude failures on s390x hotspot jdk8
  openjdk_regression/ProblemList_openjdk8.txt
Labels: bug

#1043 Remove export of JAVA_HOME from system test playlists build scripts
  buildenv/jenkins/JenkinsfileBase
  systemtest/common.xml
  systemtest/daaLoadTest/playlist.xml
  systemtest/jlm/playlist.xml
  systemtest/lambdaLoadTest/playlist.xml
  systemtest/mathLoadTest/playlist.xml
  systemtest/mauveLoadTest/playlist.xml
  systemtest/modularity/playlist.xml
  systemtest/otherLoadTest/playlist.xml
  systemtest/sharedClasses/playlist.xml
Labels: enhancement

#1055 Set separate elasticsearch_test for hotspot and openj9
  thirdparty_containers/elasticsearch/dockerfile/Dockerfile
  thirdparty_containers/elasticsearch/dockerfile/elasticsearch-test.sh
  thirdparty_containers/elasticsearch/playlist.xml
Labels: bug

#1065 Printout SHAs of the system test materials being used in builds
  systemtest/common.xml
Labels: enhancement

#1058 No longer setup on master node
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/openjdk_aarch32_linux
  buildenv/jenkins/openjdk_aarch64_linux
  buildenv/jenkins/openjdk_ppc64_aix
  buildenv/jenkins/openjdk_ppc64le_linux
  buildenv/jenkins/openjdk_s390x_linux
  buildenv/jenkins/openjdk_s390x_zos
  buildenv/jenkins/openjdk_x86-32_windows
  buildenv/jenkins/openjdk_x86-64_linux
  buildenv/jenkins/openjdk_x86-64_linux_largeHeap
  buildenv/jenkins/openjdk_x86-64_linux_xl
  buildenv/jenkins/openjdk_x86-64_mac
  buildenv/jenkins/openjdk_x86-64_mac_xl
  buildenv/jenkins/openjdk_x86-64_osx
  buildenv/jenkins/openjdk_x86-64_osx_largeHeap
  buildenv/jenkins/openjdk_x86-64_windows
Labels: bug

#1068 Update MicroProfile TCK Runners against Payara
  thirdparty_containers/payara-mp-tck/dockerfile/Dockerfile
  thirdparty_containers/payara-mp-tck/dockerfile/payara-mp-tck.sh
  thirdparty_containers/payara-mp-tck/playlist.xml
Labels: enhancement

#1070 Shorten SharedClasses Softmx test names
  systemtest/sharedClasses/playlist.xml
Labels: bug

#1074 Shorten modularity test names in playlist
  systemtest/modularity/playlist.xml
Labels: bug

#1072 Restore LargeValueExceptions.java to test bucket
  openjdk_regression/ProblemList_openjdk11-openj9.txt
  openjdk_regression/ProblemList_openjdk11.txt
  openjdk_regression/ProblemList_openjdk12-openj9.txt
  openjdk_regression/ProblemList_openjdk12.txt
  openjdk_regression/ProblemList_openjdk8-openj9.txt
Labels: bug

#1073 Archive openjdk regression tests output including diagnostic files
  buildenv/jenkins/JenkinsfileBase
  openjdk_regression/playlist.xml
Labels: enhancement

#1075 Run parallel tests out of node block
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/openjdk_aarch32_linux
  buildenv/jenkins/openjdk_aarch64_linux
  buildenv/jenkins/openjdk_ppc64_aix
  buildenv/jenkins/openjdk_ppc64le_linux
  buildenv/jenkins/openjdk_s390x_linux
  buildenv/jenkins/openjdk_s390x_zos
  buildenv/jenkins/openjdk_x86-32_windows
  buildenv/jenkins/openjdk_x86-64_linux
  buildenv/jenkins/openjdk_x86-64_linux_largeHeap
  buildenv/jenkins/openjdk_x86-64_linux_xl
  buildenv/jenkins/openjdk_x86-64_mac
  buildenv/jenkins/openjdk_x86-64_mac_xl
  buildenv/jenkins/openjdk_x86-64_osx
  buildenv/jenkins/openjdk_x86-64_osx_largeHeap
  buildenv/jenkins/openjdk_x86-64_windows
Labels: bug

#1088 Exit immediately if tests steps exit with a non-zero exit status
  thirdparty_containers/derby/build.xml
  thirdparty_containers/derby/dockerfile/derby-test.sh
  thirdparty_containers/elasticsearch/build.xml
  thirdparty_containers/example-test/build.xml
  thirdparty_containers/example-test/dockerfile/example-test.sh
  thirdparty_containers/functional-test/build.xml
  thirdparty_containers/jenkins/build.xml
  thirdparty_containers/jenkins/dockerfile/Dockerfile
  thirdparty_containers/jenkins/dockerfile/jenkins-test.sh
  thirdparty_containers/jenkins/playlist.xml
  thirdparty_containers/kafka/build.xml
  thirdparty_containers/kafka/dockerfile/kafka-test.sh
  thirdparty_containers/lucene-solr/build.xml
  thirdparty_containers/lucene-solr/dockerfile/lucene-solr-test.sh
  thirdparty_containers/openliberty-mp-tck/build.xml
  thirdparty_containers/openliberty-mp-tck/dockerfile/openliberty-mp-tck.sh
  thirdparty_containers/payara-mp-tck/build.xml
  thirdparty_containers/payara-mp-tck/dockerfile/payara-mp-tck.sh
  thirdparty_containers/scala/dockerfile/scala-test.sh
  thirdparty_containers/system-test/build.xml
  thirdparty_containers/thorntail-mp-tck/build.xml
  thirdparty_containers/thorntail-mp-tck/dockerfile/thorntail-mp-tck.sh
  thirdparty_containers/tomcat/build.xml
  thirdparty_containers/tomcat/dockerfile/tomcat-test.sh
  thirdparty_containers/wildfly/build.xml
  thirdparty_containers/wildfly/dockerfile/wildfly-test.sh
Labels: bug

#1086 Fix openjdk11-openj9 elastic test setup failure
  thirdparty_containers/elasticsearch/playlist.xml
Labels: bug

#1078 Add Wycheproof tests to the external test pool
  thirdparty_containers/wycheproof/build.xml
  thirdparty_containers/wycheproof/dockerfile/Dockerfile
  thirdparty_containers/wycheproof/dockerfile/wycheproof.sh
  thirdparty_containers/wycheproof/playlist.xml
Labels: enhancement

#1093 Replace JAVA_BIN with TEST_JDK_HOME
  buildenv/jenkins/JenkinsfileBase
  get.sh
  jck/build.xml
  jck/runtime.api/playlist.xml
  jck/runtime.lang/playlist.xml
  jck/runtime.vm/playlist.xml
  jck/runtime.xml_schema/playlist.xml
  openjdk_regression/playlist.xml
Labels: bug

#1092 Temporarily exclude jdk_jdi tests on openj9
  openjdk_regression/playlist.xml
Labels: type:openjdk

#1090 Add new Japanese era support to MBCS_Tests
  functional/MBCS_Tests/codepoint/data/UnicodeData-u32FF-jdk12.txt
  functional/MBCS_Tests/codepoint/data/UnicodeData-u32FF.txt
  functional/MBCS_Tests/codepoint/src/UnicodeDataTest.java
  functional/MBCS_Tests/unicode/data/UnicodeData-u32FF-jdk12.txt
  functional/MBCS_Tests/unicode/data/UnicodeData-u32FF.txt
  functional/MBCS_Tests/unicode/src/UnicodeChecker.java
Labels: bug

#1101 Update level of Wycheproof tests to extended
  thirdparty_containers/wycheproof/playlist.xml
Labels: bug

#1096 Enable wildfly & kafka
  thirdparty_containers/kafka/dockerfile/Dockerfile
  thirdparty_containers/kafka/dockerfile/kafka-test.sh
  thirdparty_containers/kafka/playlist.xml
  thirdparty_containers/wildfly/playlist.xml
Labels: enhancement

#1098 Running scala testssuite "jvm pos neg" in terse option
  thirdparty_containers/scala/dockerfile/Dockerfile
  thirdparty_containers/scala/dockerfile/scala-test.sh
  thirdparty_containers/scala/playlist.xml
Labels: bug

#1094 Remove function runtest sub-folder parameter
  buildenv/jenkins/JenkinsfileBase
Labels: bug
