Repository adoptium/aqa-tests, pull requests merged in 2019-07, with the labels that each got.

#1201 Replaced JAVA_BIN in external/system-test of openjdk-tests repo
  external/system-test/dockerfile/Dockerfile
  external/system-test/dockerfile/system-test.sh
  external/system-test/playlist.xml
Labels: bug

#1185 Add more renaissance perf test targets
  perf/renaissance/playlist.xml
Labels: enhancement

#1219 check git repo sha
  .gitignore
  buildenv/jenkins/JenkinsfileBase
  get.sh
  openjdk/build.xml
  systemtest/common.xml
Labels: AQA, enhancement

#1216 sanity.external: Payara-mp-tck exclude
  external/payara-mp-tck/playlist.xml
Labels: enhancement

#1220 Update ModuleLayer/BasicLayerTest exclude issue
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk12-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
Labels: bug

#1228 Fix several testcases in MBCS_Tests
  functional/MBCS_Tests/CLDR_11/src/CLDR11.java
  functional/MBCS_Tests/CLDR_11/test.sh
  functional/MBCS_Tests/Compiler/test.sh
  functional/MBCS_Tests/IDN/test.bat
  functional/MBCS_Tests/StAX/playlist.xml
  functional/MBCS_Tests/StAX/test.sh
  functional/MBCS_Tests/codepoint/src/JavaVersion.java
  functional/MBCS_Tests/coin/playlist.xml
  functional/MBCS_Tests/coin/test.sh
  functional/MBCS_Tests/env/test.bat
  functional/MBCS_Tests/file/test.bat
  functional/MBCS_Tests/file/test.sh
  functional/MBCS_Tests/i18n/test.pl
  functional/MBCS_Tests/unicode/src/JavaVersion.java
Labels: bug

#1230 Un-exclude java/lang/String/UnicodeCasingTest.java from JDK11 problem list
  openjdk/ProblemList_openjdk11-openj9.txt
Labels: bug

#1233 Un-exclude java/lang/Class/forName/arrayClass/ExceedMaxDim.java and java/lang/String/UnicodeCasingTest.java
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk12-openj9.txt
Labels: bug

#1215 Passing JenkinsFile parameter to children
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#1237 Enable jck-runtime-api-signaturetest and jck-runtime-api-javax_naming-spi on AIX
  buildenv/jenkins/JenkinsfileBase
  jck/runtime.api/playlist.xml
Labels: enhancement
