Repository adoptium/aqa-tests, pull requests merged in 2020-01, with the labels that each got.

#1521 Merge all platform specific files into one file
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/openjdk_tests
  buildenv/jenkins/testJobTemplate
  buildenv/jenkins/upstream_openjdk_tests
  get.sh
Labels: enhancement

#1544 Stop using system test prereqs from jck root
  jck/build.xml
  jck/compiler.api/playlist.xml
  jck/compiler.lang/playlist.xml
  jck/devtools.java2schema/playlist.xml
  jck/devtools.jaxws/playlist.xml
  jck/devtools.schema2java/playlist.xml
  jck/devtools.schema_bind/playlist.xml
  jck/devtools.xml_schema/playlist.xml
  jck/jck.mk
  jck/runtime.api/playlist.xml
  jck/runtime.lang/playlist.xml
  jck/runtime.vm/playlist.xml
  jck/runtime.xml_schema/playlist.xml
Labels: enhancement

#1547 Removes step to delete natives folder as git clean does the same
  jck/build.xml
Labels: bug

#1562 Using nightly JDK Image as default target
  buildenv/docker/Dockerfile
  external/build.xml
  external/derby/dockerfile/Dockerfile
  external/elasticsearch/dockerfile/Dockerfile
  external/example-test/dockerfile/Dockerfile
  external/functional-test/dockerfile/Dockerfile
  external/functional-test/dockerfile/functional-test.sh
  external/jenkins/dockerfile/Dockerfile
  external/kafka/dockerfile/Dockerfile
  external/lucene-solr/dockerfile/Dockerfile
  external/openliberty-mp-tck/dockerfile/Dockerfile
  external/payara-mp-tck/dockerfile/Dockerfile
  external/quarkus/dockerfile/Dockerfile
  external/scala/dockerfile/Dockerfile
  external/system-test/dockerfile/Dockerfile
  external/thorntail-mp-tck/dockerfile/Dockerfile
  external/tomcat/dockerfile/Dockerfile
  external/tomee/dockerfile/Dockerfile
  external/wildfly/dockerfile/Dockerfile
  external/wycheproof/dockerfile/Dockerfile
Labels: bug

#1557 Update ASM to 7.3 + Add enable preview option for HCRLateAttachWorkload test on jdk 14
  buildenv/jenkins/getDependency
  system/otherLoadTest/playlist.xml
Labels: bug

#1551 Only fetch PR refs if SHA not found in unshallow first
  get.sh
Labels: bug

#1534 Move post stage to finally
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#1568 Use enable preview option in 11+ sdks for HCRLateAttachWorkload test
  system/otherLoadTest/playlist.xml
Labels: bug

#1565 Update External functional-test
  external/functional-test/dockerfile/Dockerfile
  external/functional-test/dockerfile/functional-test.sh
  external/functional-test/playlist.xml
Labels: bug

#1561 Remove extra run_configure step
  maketest.sh
  openjdk/build.xml
Labels: enhancement

#1510 Revamped Dockerfiles for various Test Cases
  external/derby/dockerfile/Dockerfile
  external/jenkins/dockerfile/Dockerfile
  external/kafka/dockerfile/Dockerfile
  external/kafka/dockerfile/kafka-test.sh
  external/lucene-solr/dockerfile/Dockerfile
  external/openliberty-mp-tck/dockerfile/Dockerfile
  external/payara-mp-tck/dockerfile/Dockerfile
  external/scala/dockerfile/Dockerfile
  external/thorntail-mp-tck/dockerfile/Dockerfile
  external/tomcat/dockerfile/Dockerfile
  external/tomcat/dockerfile/tomcat-test.sh
  external/tomee/dockerfile/Dockerfile
  external/wildfly/dockerfile/Dockerfile
  external/wildfly/dockerfile/wildfly-test.sh
  external/wycheproof/dockerfile/Dockerfile
  external/wycheproof/dockerfile/wycheproof.sh
Labels: bug

#1566 If junit test run there should always be test results
  external/elasticsearch/dockerfile/elasticsearch-test.sh
  external/jenkins/dockerfile/jenkins-test.sh
  external/openliberty-mp-tck/dockerfile/openliberty-mp-tck.sh
  external/payara-mp-tck/dockerfile/payara-mp-tck.sh
  external/thorntail-mp-tck/dockerfile/thorntail-mp-tck.sh
  external/tomee/dockerfile/tomee-test.sh
  external/wycheproof/dockerfile/wycheproof.sh
Labels: bug

#1569 Update External system-test
  external/system-test/dockerfile/Dockerfile
  external/system-test/dockerfile/system-test.sh
  external/system-test/playlist.xml
Labels: bug

#1532 Update to use API v3
  get.sh
Labels: enhancement

#1570 Update TKG running process
  buildenv/docker/mktest.sh
  external/functional-test/dockerfile/functional-test.sh
  external/system-test/dockerfile/system-test.sh
  jck/README.md
Labels: bug

#1572 Temporarily increase verbosity on curl for SDK fetch
  buildenv/jenkins/JenkinsfileBase
  get.sh
Labels: bug

#1582 Exclude CondyNestedResolutionTest on openj9 jdk11 and jdk13
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
Labels: bug

#1583 Java NIO Triage
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk11.txt
  openjdk/ProblemList_openjdk13-openj9.txt
  openjdk/ProblemList_openjdk13.txt
Labels: bug

#1585 No tar=gtar on aix
  buildenv/jenkins/JenkinsfileBase
Labels: aix, bug

#1586 Do not require GNU tar options when downloading jtreg
  openjdk/build.xml
Labels: aix

#1590 Ensure openj9 attach api is enabled for jck jvmti tests
  jck/runtime.vm/playlist.xml
Labels: enhancement

#1591 Add ibm tag to all openj9 system tests
  system/common.xml
  system/daaLoadTest/playlist.xml
  system/jlm/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/modularity/playlist.xml
  system/otherLoadTest/playlist.xml
  system/sharedClasses/playlist.xml
Labels: enhancement
