Repository adoptium/aqa-tests, pull requests merged in 2020-04, with the labels that each got.

#1698 Convert External MP-TCK Tests
  external/derby/build.xml
  external/openliberty-mp-tck/build.xml
  external/openliberty-mp-tck/playlist.xml
  external/payara-mp-tck/build.xml
  external/payara-mp-tck/playlist.xml
  external/thorntail-mp-tck/build.xml
  external/thorntail-mp-tck/dockerfile/thorntail-mp-tck.sh
  external/thorntail-mp-tck/playlist.xml
Labels: enhancement

#1707 Support openjdk Jtreg on zOS
  get.sh
  openjdk/build.xml
  openjdk/openjdk.mk
Labels: enhancement

#1710 OpenJ9 AArch64: excluding tests known to timeout
  openjdk/ProblemList_openjdk11-openj9.txt
Labels: bug

#1716 OpenJ9 AArch64: Exclude two ProcessBuilder tests
  openjdk/ProblemList_openjdk11-openj9.txt
Labels: bug

#1717 AArch64: Exclude SC_Softmx_JitAot_Linux test
  system/sharedClasses/playlist.xml
Labels: enhancement

#1719 Exclude EvalArraysAsList.sh
  openjdk/ProblemList_openjdk8.txt
Labels: bug

#1724 Exclude multiple failing hotspot tests on windows
  openjdk/ProblemList_openjdk8.txt
Labels: bug

#1723 Update CLDR_11 for 11.0.7, language_tag and StAX testcases
  functional/MBCS_Tests/CLDR_11/src/CLDR11-ja-JP.properties
  functional/MBCS_Tests/CLDR_11/src/CLDR11-ko-KR.properties
  functional/MBCS_Tests/CLDR_11/src/CLDR11-zh-CN.properties
  functional/MBCS_Tests/CLDR_11/src/CLDR11-zh-TW.properties
  functional/MBCS_Tests/CLDR_11/src/JavaVersion.java
  functional/MBCS_Tests/CLDR_11/tap_compare.pl
  functional/MBCS_Tests/CLDR_11/test.bat
  functional/MBCS_Tests/CLDR_11/test.sh
  functional/MBCS_Tests/StAX/expected/Darwin_zh_CN.UTF-8/read_cursor.html
  functional/MBCS_Tests/StAX/expected/Darwin_zh_CN.UTF-8/read_event.html
  functional/MBCS_Tests/StAX/expected/Darwin_zh_CN.UTF-8/write_cursor.xml
  functional/MBCS_Tests/StAX/expected/Darwin_zh_CN.UTF-8/write_event.xml
  functional/MBCS_Tests/StAX/expected/Darwin_zh_TW.UTF-8/read_cursor.html
  functional/MBCS_Tests/StAX/expected/Darwin_zh_TW.UTF-8/read_event.html
  functional/MBCS_Tests/StAX/expected/Darwin_zh_TW.UTF-8/write_cursor.xml
  functional/MBCS_Tests/StAX/expected/Darwin_zh_TW.UTF-8/write_event.xml
  functional/MBCS_Tests/language_tag/build.xml
  functional/MBCS_Tests/language_tag/src/CNTagTest.java
  functional/MBCS_Tests/language_tag/src/JPTagTest.java
  functional/MBCS_Tests/language_tag/src/KRTagTest.java
  functional/MBCS_Tests/language_tag/src/TWTagTest.java
  functional/MBCS_Tests/language_tag/src/USTagTest.java
Labels: enhancement

#1726 Enable OpenJ9 Attach API for JCK tests on zOS
  buildenv/jenkins/testJobTemplate
Labels: bug

#1734 Exclude JDI Tests
  openjdk/ProblemList_openjdk11.txt
  openjdk/ProblemList_openjdk14.txt
Labels: bug

#1735 Exclude JBS Bugs
  openjdk/ProblemList_openjdk8.txt
Labels: bug

#1738 Exclude Failing scaffold tests on s390x
  openjdk/ProblemList_openjdk8.txt
Labels: bug

#1739 OpenJ9 AArch64: Exclude a test that depends on GC
  openjdk/ProblemList_openjdk11-openj9.txt
Labels: bug

#1740 Exclude CheckZombieLockTest on windows_x64
  openjdk/ProblemList_openjdk11-openj9.txt
Labels: bug

#1741 Exclude ProcessAttachTest.sh on mac
  openjdk/ProblemList_openjdk8.txt
Labels: bug

#1743 Exclude TestAllocInNewTLAB.java
  openjdk/ProblemList_openjdk14.txt
Labels: bug

#1745 Add x86 to generic-arch
  openjdk/README.md
Labels: docs

#1733 Exclude tests
  openjdk/ProblemList_openjdk8.txt
Labels: bug

#1727 Add Humble Benchmarks
  perf/bumbleBench/playlist.xml
Labels: enhancement

#1749 Re-exclude tests on z-linux
  openjdk/ProblemList_openjdk8.txt
Labels: bug

#1751 Retry getJtreg 5 times before failing
  openjdk/build.xml
Labels: bug

#1747 Update getJtreg task logic
  openjdk/build.xml
Labels: enhancement

#1742 Add action example
  .github/workflows/actionExample.yml
Labels: enhancement

#1753 Enable the Attach API for openjdk jobs on z/OS
  openjdk/openjdk.mk
Labels: bug

#1759 Disable actions for examples
  .github/workflows/actionExample.yml
Labels: enhancement

#1762 Ignore -jfr and -static-libs filenames when testing upstream
  buildenv/jenkins/upstream_openjdk_tests
Labels: bug

#1763 Exclude Version.java on JDK8
  openjdk/ProblemList_openjdk8.txt
Labels: bug
