Repository adoptium/aqa-tests, pull requests merged in 2020-03, with the labels that each got.

#1668 Upgrade to ASM 7.3.1
  buildenv/jenkins/getDependency
Labels: bug

#1660 Use external.sh and build_image.sh for more docker image tag coverage
  external/build.xml
  external/camel/build.xml
  external/camel/playlist.xml
  external/derby/build.xml
  external/derby/playlist.xml
  external/external.sh
  external/jenkins/build.xml
  external/jenkins/playlist.xml
  external/kafka/build.xml
  external/kafka/playlist.xml
Labels: enhancement

#1669 Reinstate excluded test
  openjdk/ProblemList_openjdk14.txt
  openjdk/ProblemList_openjdk15.txt
Labels: bug

#1684 Adding MixedLoadTest to otherLoadTest as part of Load_Level_4 playlist
  system/otherLoadTest/playlist.xml
Labels: type:system

#1686 Allow AUTO_DETECT to be set in template
  buildenv/jenkins/testJobTemplate
Labels: bug

#1688 PR for Issue 1681:jdk14 repo is now jdk14u
  openjdk/build.xml
Labels: enhancement

#1689 Update exclusion issue url
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk14-openj9.txt
  openjdk/ProblemList_openjdk15-openj9.txt
Labels: bug

#1682 added cleaning leaving core files in tmp folder
  buildenv/jenkins/JenkinsfileBase
Labels: bug

#1694 Un-exclude SymmetricRangeTests for jdk11 & jdk15
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk15-openj9.txt
Labels: bug

#1693 Converted External Test to new Framework
  .gitignore
  external/common_functions.sh
  external/dockerfile_functions.sh
  external/functional-test/playlist.xml
  external/lucene-solr/build.xml
  external/lucene-solr/playlist.xml
  external/quarkus/build.xml
  external/quarkus/dockerfile/quarkus-test.sh
  external/quarkus/playlist.xml
  external/scala/build.xml
  external/scala/playlist.xml
  external/system-test/build.xml
  external/system-test/playlist.xml
  external/tomcat/build.xml
  external/tomcat/playlist.xml
  external/tomee/build.xml
  external/tomee/playlist.xml
  external/wildfly/build.xml
  external/wildfly/playlist.xml
  external/wycheproof/build.xml
  external/wycheproof/dockerfile/wycheproof.sh
  external/wycheproof/playlist.xml
Labels: enhancement

#1695 Regroup sanity according to openjdk tier1
  openjdk/ProblemList_openjdk14-openj9.txt
  openjdk/ProblemList_openjdk14.txt
  openjdk/ProblemList_openjdk15-openj9.txt
  openjdk/ProblemList_openjdk15.txt
  openjdk/playlist.xml
Labels: enhancement

#1692 Auto download test-images and debug-images
  buildenv/jenkins/JenkinsfileBase
  get.sh
Labels: enhancement
