Repository adoptium/aqa-tests, pull requests merged in 2020-07, with the labels that each got.

#1847 Update CLDR_11 for 11.0.8 and more
  functional/MBCS_Tests/CLDR_11/src/CLDR11-ja-JP.properties
  functional/MBCS_Tests/CLDR_11/src/CLDR11-ko-KR.properties
  functional/MBCS_Tests/CLDR_11/src/CLDR11-zh-CN.properties
  functional/MBCS_Tests/CLDR_11/src/CLDR11-zh-TW.properties
  functional/MBCS_Tests/CLDR_11/src/cldr.pl
  functional/MBCS_Tests/CLDR_11/tap_compare.pl
  functional/MBCS_Tests/CLDR_11/test.bat
  functional/MBCS_Tests/Compiler/data/expected_windows_ja.txt
  functional/MBCS_Tests/Compiler/data/expected_windows_ko.txt
  functional/MBCS_Tests/IDN/data/expected_windows_ja.txt
  functional/MBCS_Tests/IDN/data/expected_windows_ko.txt
  functional/MBCS_Tests/StAX/data2/setup_zh-cn.bat
  functional/MBCS_Tests/StAX/data2/setup_zh-tw.bat
  functional/MBCS_Tests/annotation/expected/aix_JA_JP.UTF-8.txt
  functional/MBCS_Tests/annotation/expected/aix_Ja_JP.IBM-943.txt
  functional/MBCS_Tests/annotation/expected/aix_KO_KR.UTF-8.txt
  functional/MBCS_Tests/annotation/expected/aix_ja_JP.IBM-eucJP.txt
  functional/MBCS_Tests/annotation/expected/aix_ko_KR.IBM-eucKR.txt
  functional/MBCS_Tests/annotation/expected/linux_ja_JP.UTF-8.txt
  functional/MBCS_Tests/annotation/expected/linux_ko_KR.UTF-8.txt
  functional/MBCS_Tests/annotation/expected/win_ja.expected.txt
  functional/MBCS_Tests/annotation/expected/win_ko.expected.txt
  functional/MBCS_Tests/annotation/resultCheck.pl
  functional/MBCS_Tests/annotation/src/AnnotationProcessor.java
  functional/MBCS_Tests/annotation/src/AnnotationProcessor11.java
  functional/MBCS_Tests/annotation/src/AnnotationProcessor7.java
  functional/MBCS_Tests/annotation/src/AnnotationProcessor8.java
  functional/MBCS_Tests/codepage/data/WIN_MS932.txt
  functional/MBCS_Tests/codepage/data/WIN_MS949.txt
  functional/MBCS_Tests/codepage/src/UCompare.java~
  functional/MBCS_Tests/data/setup_zh-cn.bat
  functional/MBCS_Tests/data/setup_zh-tw.bat
  functional/MBCS_Tests/env/data/expected_windows_ja.txt
  functional/MBCS_Tests/env/data/expected_windows_ko.txt
  functional/MBCS_Tests/formatter/data/expected_windows_ja.txt
  functional/MBCS_Tests/formatter/data/expected_windows_ko.txt
  functional/MBCS_Tests/pref/data/expected_windows_ja.txt
  functional/MBCS_Tests/pref/data/expected_windows_ko.txt
  functional/MBCS_Tests/scanner/expected/windows_ja.txt
  functional/MBCS_Tests/scanner/expected/windows_ko.txt
  functional/MBCS_Tests/urlclassloader/src/UrlClassClose.java
Labels: bug

#1835 Start an X11 server for openjdk tests on AIX
  buildenv/jenkins/JenkinsfileBase
  openjdk/playlist.xml
Labels: enhancement

#1868 Removing wget call in getDependency with curl
  buildenv/jenkins/getDependency
Labels: bug

#1865 Cache TRSS JSON output (Smart Parallelization approach 3)
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/getTRSSOutput
Labels: enhancement

#1870 Unexclude tests affected by bad hostname setup
  openjdk/ProblemList_openjdk8.txt
Labels: bug

#1885 Add -Xtrace:maximal=all{level2} in JCK
  jck/jck.mk
Labels: enhancement

#1884 Run All available JCK targets in all Java versions
  jck/compiler.api/playlist.xml
  jck/compiler.lang/playlist.xml
  jck/runtime.api/playlist.xml
  jck/runtime.lang/playlist.xml
  jck/runtime.vm/playlist.xml
Labels: enhancement, type:jck

#1890 Add docker_prune as depends in clean_image target
  external/build.xml
Labels: enhancement

#1886 Update playlist.xml files for JDK8 AIX ja_JP, zh_CN and zh_TW and data of jdbc41 for AIX zh_CN in MBCS_Tests
  functional/MBCS_Tests/Compiler/playlist.xml
  functional/MBCS_Tests/IDN/playlist.xml
  functional/MBCS_Tests/annotation/playlist.xml
  functional/MBCS_Tests/codepage/playlist.xml
  functional/MBCS_Tests/coin/playlist.xml
  functional/MBCS_Tests/env/playlist.xml
  functional/MBCS_Tests/file/playlist.xml
  functional/MBCS_Tests/jdbc41/data/setjdbc41_AIX_zh_CN.IBM-eucCN
  functional/MBCS_Tests/jdbc41/expected/AIX_zh_CN.IBM-eucCN_auto.txt
  functional/MBCS_Tests/jdbc41/expected/AIX_zh_CN.IBM-eucCN_row.txt
  functional/MBCS_Tests/jdbc41/playlist.xml
  functional/MBCS_Tests/nio/playlist.xml
  functional/MBCS_Tests/pref/playlist.xml
  functional/MBCS_Tests/regex/playlist.xml
  functional/MBCS_Tests/scanner/playlist.xml
  functional/MBCS_Tests/scanner/test.sh
  functional/MBCS_Tests/urlclassloader/playlist.xml
Labels: bug

#1896 Excluding Zip64SizeTest on linux-ppc64le until we can run it
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk11.txt
  openjdk/ProblemList_openjdk14-openj9.txt
  openjdk/ProblemList_openjdk14.txt
  openjdk/ProblemList_openjdk15-openj9.txt
  openjdk/ProblemList_openjdk15.txt
Labels: bug

#1899 Add full set of supported versions for java_rmi test
  jck/compiler.api/playlist.xml
Labels: bug

#1876 Add JDK_REPO and JDK_BRANCH
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/testJobTemplate
  openjdk/build.xml
Labels: enhancement

#1902 Revert "Excluding Zip64SizeTest on linux-ppc64le until we can run it …
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk11.txt
  openjdk/ProblemList_openjdk14-openj9.txt
  openjdk/ProblemList_openjdk14.txt
  openjdk/ProblemList_openjdk15-openj9.txt
  openjdk/ProblemList_openjdk15.txt
Labels: bug

#1901 Update MBCS_Tests.formatter for JDK14
  functional/MBCS_Tests/formatter/src/FormatterTest2.java
Labels: bug

#1907 Exclude failing tests on linux-aarch64
  openjdk/ProblemList_openjdk14.txt
Labels: bug

#1904 set a default ProblemList file
  openjdk/openjdk.mk
  openjdk/playlist.xml
Labels: enhancement

#1906 Exclude ProblemList files for HotSpot test suits
  openjdk/playlist.xml
Labels: bug

#1919 Support extracting pax files
  get.sh
Labels: enhancement

#1910 Add triggers based on regular intervals
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#1913 Move openjdk java/util/zip/ZipFile/TestCleaner to special
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk15-openj9.txt
  openjdk/playlist.xml
Labels: bug

#1922 Set JDK_REPO for zos as is if it's using ssh.
  openjdk/build.xml
Labels: bug

#1925 Re-include hidden classes related testing
  openjdk/ProblemList_openjdk15-openj9.txt
Labels: bug

#1927 Split up verifier test target into sub-tests based on subfolders
  jck/jck.mk
  jck/runtime.vm/playlist.xml
Labels: enhancement, type:jck

#1926 Set CheckHandles.java as separate native tests
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk11.txt
  openjdk/playlist.xml
Labels: enhancement

#1917 Ability to Dynamically Set CPU Affinities for Benchmarking
  perf/affinity.sh
  perf/renaissance/build.xml
  perf/renaissance/playlist.xml
  perf/run_with_affinity.sh
Labels: enhancement
