Repository adoptium/aqa-tests, pull requests merged in 2020-12, with the labels that each got.

#2079 Add check for jck update
  jck/build.xml
Labels: enhancement

#2081 Add x86-64_linux_mixed in openjdk_tests
  buildenv/jenkins/openjdk_tests
Labels: enhancement

#2080 Exclude ProcessBuilder Basic_id0 test on aix
  openjdk/ProblemList_openjdk11-openj9.txt
Labels: bug

#2035 Remove RELEASE_TAG in test scripts
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/testJobTemplate
  openjdk/build.xml
Labels: enhancement

#2089 Shorten modularity test names to suit Windows MAX_PATH limit
  system/modularity/playlist.xml
Labels: bug

#2087 Add mixed platforms
  buildenv/jenkins/openjdk_tests
Labels: enhancement

#2099 Temporarily exclude failing system tests from z/OS
  system/jlm/playlist.xml
  system/modularity/playlist.xml
  system/otherLoadTest/playlist.xml
Labels: bug

#2101 Update --system to --global to avoid Admin permission
  openjdk/build.xml
Labels: bug

#2092 Fix 11.0.10 CLDR_11 data and tool
  functional/MBCS_Tests/CLDR_11/src/CLDR11-ja-JP.properties
  functional/MBCS_Tests/CLDR_11/src/CLDR11-ko-KR.properties
  functional/MBCS_Tests/CLDR_11/src/CLDR11-zh-CN.properties
  functional/MBCS_Tests/CLDR_11/src/CLDR11-zh-TW.properties
  functional/MBCS_Tests/CLDR_11/src/README.tools
  functional/MBCS_Tests/CLDR_11/src/cldr.pl
Labels: bug

#2095 Update userGuide with new exclude feature
  doc/userGuide.md
Labels: docs

#2102 Increase machine limit from 1/2 to 3/4 of the available machines
  buildenv/jenkins/JenkinsfileBase
Labels: bug

#2103 Update disabled elements in playlist files
  external/elasticsearch/playlist.xml
  external/payara-mp-tck/playlist.xml
  external/quarkus/playlist.xml
  external/quarkus_openshift/playlist.xml
  external/thorntail-mp-tck/playlist.xml
  jck/runtime.vm/playlist.xml
  openjdk/playlist.xml
  perf/bumbleBench/playlist.xml
  perf/dacapo/playlist.xml
  perf/renaissance/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/modularity/playlist.xml
Labels: enhancement

#2106 Exclude PlatformLoggerTest.java for all platforms
  openjdk/ProblemList_openjdk8-openj9.txt
Labels: aix, bug

#2110 Shorten Mauve load test names
  system/mauveLoadTest/playlist.xml
Labels: bug

#2108 get third party lib for openjdk test
  openjdk/build.xml
Labels: enhancement

#2086 Remove git clean from jck git logic
  jck/build.xml
Labels: enhancement

#2114 Revert: Add -Xdump NPE option to jdk_lang_j9 for debug
  openjdk/playlist.xml
Labels: bug

#2107 Add MiniMix_5min target
  system/otherLoadTest/playlist.xml
Labels: enhancement

#2093 Add spring and netty tests
  buildenv/jenkins/JenkinsfileBase
  external/common_functions.sh
  external/example-test/build.xml
  external/netty/build.xml
  external/netty/dockerfile/netty-test.sh
  external/netty/playlist.xml
  external/spring/build.xml
  external/spring/dockerfile/spring-test.sh
  external/spring/playlist.xml
Labels: enhancement

#2121 Move windows Java process kill logic to JenkinsfileBase and enhance
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/openjdk_tests
  maketest.sh
Labels: bug

#2126 Update ASM to 9.0
  buildenv/jenkins/getDependency
Labels: enhancement

#2130 fix wrong openjdk checkout directory
  openjdk/build.xml
Labels: bug
