Repository adoptium/aqa-tests, pull requests merged in 2020-11, with the labels that each got.

#2034 Extend Liberty to Other Platforms & Bug Fixes for Affinity Tool
  perf/affinity.sh
  perf/liberty/README.md
  perf/liberty/configs/dt7_throughput.sh
  perf/liberty/playlist.xml
  perf/liberty/scripts/bin/configure_liberty.sh
  perf/liberty/scripts/bin/sufp_benchmark.sh
  perf/liberty/scripts/resource/aix_footprint.awk
  perf/renaissance/playlist.xml
Labels: bug

#2040 Use disabled variation tag in playlist.xml
  system/daaLoadTest/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/otherLoadTest/playlist.xml
Labels: enhancement

#2046 Renable HCRLateAttachWorkload tests on Windows
  system/otherLoadTest/playlist.xml
Labels: bug

#2049 Add TLS / SSL functional tests
  .gitignore
  functional/security/build.xml
  functional/security/playlist.xml
  functional/security/src/net/adoptopenjdk/test/DefaultTlsFunctionalTest.java
  functional/security/src/net/adoptopenjdk/test/Tls13FunctionalTest.java
  functional/security/testng.xml
Labels: enhancement

#2052 Remove trailing space from jck_runtimes_src_dir
  jck/build.xml
Labels: bug

#2045 Update jtreg to 5.1 for jdk 15 and 15+
  openjdk/build.xml
Labels: enhancement

#2044 Use single quotation mark in java-args
  system/daaLoadTest/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/otherLoadTest/playlist.xml
  system/systemtest.mk
Labels: bug

#2053 Update autoTestPR workflow
  .github/workflows/autoTestPR.yml
Labels: enhancement

#1979 Add synthetic GC double map test to Mac OSX
  functional/SyntheticGCWorkload/playlist.xml
Labels: enhancement

#2048 Reenable JlinkTest_RequiredMod on osx
  system/modularity/playlist.xml
Labels: bug

#2055 Add user guide for exclude feature
  doc/userGuide.md
Labels: docs

#2056 Use JDK_IMPL_BASE to distinguish implementation
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#2039 get.sh: allow tarball extraction with Solaris tar
  functional/SyntheticGCWorkload/run_test.sh
  get.sh
  maketest.sh
  openjdk/build.xml
  perf/affinity.sh
  perf/liberty/scripts/bin/common_utils.sh
  perf/liberty/scripts/bin/database_utils.sh
  perf/liberty/scripts/bin/sufp_benchmark.sh
  perf/liberty/scripts/bin/throughput_benchmark.sh
  perf/liberty/scripts/resource/client_scripts/cpu.sh
  perf/liberty/scripts/resource/client_scripts/trade.sh
Labels: enhancement

#2059 maketest.sh: Add process cleanup for Windows at the end of testing
  maketest.sh
Labels: bug

#2064 Test crosscheck
  jck/jck_target_folder_check/README.md
  jck/jck_target_folder_check/jck_target_folder_check.sh
  jck/runtime.api/playlist.xml
Labels: enhancement

#2071 Change Mode140 to Mode145 in special.system tests
  system/daaLoadTest/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/otherLoadTest/playlist.xml
Labels: enhancement

#2073 Run special.system tests with Mode645
  system/daaLoadTest/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/otherLoadTest/playlist.xml
Labels: enhancement
