Repository adoptium/aqa-tests, pull requests merged in 2020-10, with the labels that each got.

#1988 Remove the logic of using master node to get user email
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/openjdk_tests
Labels: bug

#1987 Enhance PARALLEL=Iteration
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#1956 Ash vs Bash
  external/common_functions.sh
Labels: enhancement

#1999 Add api/java_lang/System to jck.sanity
  jck/runtime.api/playlist.xml
Labels: enhancement

#1990 copy TAP if child is UNSTABLE
  buildenv/jenkins/JenkinsfileBase
Labels: bug

#2001 Remove some java/foreign excludes
  openjdk/ProblemList_openjdk15-openj9.txt
Labels: bug

#1996 Exclude tomee and openliberty-mp-tck for s390x jdk8 Hotspot
  external/openliberty-mp-tck/playlist.xml
  external/tomee/playlist.xml
Labels: bug

#2009 Reinstate ConcurrentLoadTest
  system/otherLoadTest/playlist.xml
Labels: bug

#2003 Renable JlmLocal and Thread tests
  system/jlm/playlist.xml
Labels: enhancement

#2021 Use Affinity & Update Version for Liberty
  perf/affinity.sh
  perf/liberty/build.xml
  perf/liberty/configs/dt7_sufp.sh
  perf/liberty/configs/dt7_throughput.sh
  perf/liberty/playlist.xml
  perf/liberty/scripts/bin/configure_liberty.sh
  perf/liberty/scripts/bin/database_utils.sh
  perf/run_with_affinity.sh
Labels: enhancement

#2025 Allow option to skip TCK git update
  jck/build.xml
Labels: enhancement

#2023 Add diff.sh to compare file contents
  jck/diff/README.md
  jck/diff/diff.sh
Labels: enhancement

#2019 copy TAP from UNSTABLE child
  buildenv/jenkins/JenkinsfileBase
Labels: bug

#2018 Excludes for known failures in hs jdk15
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk12-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
  openjdk/ProblemList_openjdk14-openj9.txt
  openjdk/ProblemList_openjdk15-openj9.txt
  openjdk/ProblemList_openjdk15.txt
  openjdk/ProblemList_openjdk16-openj9.txt
  openjdk/ProblemList_openjdk8.txt
Labels: test excluded

#1977 Add Push or PR test build workflow file
  .github/workflows/PushOrPRtestbuild.yml
  openjdk/ProblemList_openjdk15-openj9.txt
Labels: enhancement
