Repository adoptium/aqa-tests, pull requests merged in 2021-03, with the labels that each got.

#2314 Change Renaissance 0.9.0 to 0.11.0 in build.xml
  perf/renaissance/build.xml
Labels: enhancement

#2287 Handle a git command's request for a username on Windows
  openjdk/build.xml
Labels: bug

#2318 Ignore leading and trailing whitespace in parsing of comments (runAqa.yml)
  .github/workflows/runAqaArgParse.py
Labels: bug, canosp_w21

#2341 Fix mapping from x86-64_mac to macos GitHub runner in Comment Triggered PR Build Workflow
  .github/workflows/runAqaArgParse.py
Labels: bug, canosp_w21

#2335 Update timeout logic
  buildenv/jenkins/openjdk_tests
Labels: enhancement

#2345 Allow for cgroups in MEMORY_SIZE detection
  openjdk/openjdk.mk
Labels: bug

#2388 Excluding CheckHandles.java test from 32bit Windows
  openjdk/playlist.xml
Labels: bug

#2313 reportStatus job enhancements (runAqa.yml)
  .github/workflows/runAqa.yml
Labels: canosp_w21

#2328 Excluding ResetPeakMemoryUsage on openj9
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk12-openj9.txt
  openjdk/ProblemList_openjdk13-openj9.txt
  openjdk/ProblemList_openjdk14-openj9.txt
  openjdk/ProblemList_openjdk15-openj9.txt
  openjdk/ProblemList_openjdk16-openj9.txt
  openjdk/ProblemList_openjdk17-openj9.txt
Labels: enhancement

#2402 Add customized TKG option to Comment-Triggered PR Build workflow
  .github/workflows/runAqa.yml
  .github/workflows/runAqaArgParse.py
Labels: canosp_w21, enhancement

#2322 Allow the use of a customized SDK in comment triggered PR builds (runAqa.yml)
  .github/workflows/runAqa.yml
  .github/workflows/runAqaArgParse.py
Labels: canosp_w21, enhancement

#2403 Prevent from retrying when curl command is missing
  get.sh
Labels: canosp_w21

#2397 Enable Dynamic agent
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/openjdk_tests
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#2416 Exclude jdk8 hotspot s390xLinux and Windows com/sun/jdi sanity.openjdk testcases
  openjdk/ProblemList_openjdk8.txt
Labels: bug

#2411 Reinstate PatMod_PlatMod and PatModImg_PlatMod systemtests on AIX
  system/modularity/playlist.xml
Labels: bug

#2413 Add --add-opens for java.lang + java.io in system_custom by default
  system/otherLoadTest/playlist.xml
  system/systemtest.mk
Labels: enhancement

#2375 Separate Jenkins Parameters into Categories
  buildenv/jenkins/testJobTemplate
Labels: canosp_w21

#2424 Add documentation for the Run AQA (Comment-Triggered PR Builds) workflow
  doc/RunAqa.md
Labels: canosp_w21

#2425 Test Autogen: Reset JCK_GIT_REPO every loop
  buildenv/jenkins/testJobTemplate
Labels: bug
