Repository adoptium/aqa-tests, pull requests merged in 2021-04, with the labels that each got.

#2426 Only generate child jobs if they do not exist
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#2414 Add JDK_NATIVE_OPTIONS to all openjdk test targets
  openjdk/playlist.xml
Labels: canosp_w21

#2419 Exclude long-running tests on s390 JDK8 HS extended.openjdk tests
  openjdk/excludes/ProblemList_openjdk8.txt
Labels: bug

#2452 Completed prep work for netty tests
  external/netty/README.md
  external/netty/test.properties
Labels: enhancement

#2457 Add help command to Run AQA (Comment-Triggered PR Build) Workflow
  .github/workflows/runAqaArgParse.py
  doc/RunAqa.md
Labels: canosp_w21, enhancement

#2451 Completed prep work for camel tests
  external/camel/README.md
  external/camel/dockerfile/Dockerfile
  external/camel/test.properties
Labels: enhancement

#2465 Run AQA Workflow: Use runAqaArgParse.py script from TKG to remove duplicate code.
  .github/workflows/runAqa.yml
  .github/workflows/runAqaArgParse.py
  .github/workflows/runAqaConfig.json
  doc/RunAqa.md
Labels: canosp_w21

#2438 Update playlist to use new disable features
  openjdk/playlist.xml
Labels: enhancement

#2468 Renaissance als failure
  perf/perf.mk
  perf/renaissance/build.xml
  perf/renaissance/playlist.xml
Labels: bug

#2473 Tweetest Prep work for kafka tests
  external/kafka/README.md
  external/kafka/dockerfile/Dockerfile
  external/kafka/test.properties
Labels: enhancement

#2454 Completed prep work for quarkus_openshift tests
  external/quarkus_openshift/README.md
  external/quarkus_openshift/test.properties
Labels: enhancement

#2463 Added a README.md & test.properties file to the wycheproof docs
  external/wycheproof/README.md
  external/wycheproof/dockerfile/Dockerfile
  external/wycheproof/test.properties
Labels: enhancement

#2456 Update external tests to allow for autogen of Docker images for jdk16+
  external/common_functions.sh
Labels: enhancement

#2406 Check if the curl URL is invalid before unzip the download file
  get.sh
Labels: bug, canosp_w21

#2534 Replace Korean test data files on MBCS_Tests
  functional/MBCS_Tests/i18n/data/aix_KO_KR.UTF-8.txt
  functional/MBCS_Tests/i18n/data/aix_ko_KR.IBM-eucKR.txt
  functional/MBCS_Tests/i18n/data/aix_ko_KR.UTF-8.txt.s
  functional/MBCS_Tests/i18n/data/linux_ko_KR.UTF-8.txt
  functional/MBCS_Tests/i18n/data/win_ko.txt
  functional/MBCS_Tests/i18n/expected/aix_KO_KR.UTF-8/BreakIteratorTest.out
  functional/MBCS_Tests/i18n/expected/aix_ko_KR.IBM-eucKR/BreakIteratorTest.out
  functional/MBCS_Tests/i18n/expected/linux_ko_KR.UTF-8/BreakIteratorTest.out
  functional/MBCS_Tests/i18n/expected/win_ko/BreakIteratorTest.out
  functional/MBCS_Tests/regex/data/AIX_KO_KR.UTF-8.txt
  functional/MBCS_Tests/regex/data/AIX_ko_KR.IBM-eucKR.txt
  functional/MBCS_Tests/regex/data/Linux_ko_KR.UTF-8.txt
  functional/MBCS_Tests/regex/data/expected_AIX_KO_KR.UTF-8
  functional/MBCS_Tests/regex/data/expected_AIX_ko_KR.IBM-eucKR
  functional/MBCS_Tests/regex/data/expected_Linux_ko_KR.UTF-8
  functional/MBCS_Tests/regex/data/result_win_ko.txt
  functional/MBCS_Tests/regex/data/setup_win_ko.bat
  functional/MBCS_Tests/regex/data/setup_windows_ko.properties
  functional/MBCS_Tests/regex/data/test_AIX_KO_KR.UTF-8
  functional/MBCS_Tests/regex/data/test_AIX_ko_KR.IBM-eucKR
  functional/MBCS_Tests/regex/data/test_Linux_ko_KR.UTF-8
  functional/MBCS_Tests/regex/data/win_ko.txt
Labels: bug

#2524 Exclude DeadSSLLdapTimeoutTest on jdk8
  openjdk/excludes/ProblemList_openjdk8-openj9.txt
  openjdk/excludes/ProblemList_openjdk8.txt
Labels: bug

#2532 Disable JFR tests on AIX.
  openjdk/playlist.xml
  perf/dacapo/playlist.xml
Labels: enhancement

#2521 Added three system test repo specific fields to grinder job template
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#2423 Excluding openj9 specific tests and zos specific tests for jdk11 and later releases
  openjdk/excludes/ProblemList_openjdk11-openj9.txt
  openjdk/excludes/ProblemList_openjdk12-openj9.txt
  openjdk/excludes/ProblemList_openjdk13-openj9.txt
  openjdk/excludes/ProblemList_openjdk14-openj9.txt
  openjdk/excludes/ProblemList_openjdk15-openj9.txt
  openjdk/excludes/ProblemList_openjdk16-openj9.txt
  openjdk/excludes/ProblemList_openjdk17-openj9.txt
Labels: bug

#2488 Added system_custom example in testJobTemplate
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#2538 add README, test.properties files
  external/jacoco/README.md
  external/jacoco/dockerfile/Dockerfile
  external/jacoco/test.properties
Labels: docs

#2498 Added how to run live monitor and test count scripts
  doc/userGuide.md
Labels: enhancement

#2548 Exclude JCK 16 targets that fail due to infra issue
  jck/runtime.api/playlist.xml
Labels: bug

#2552 Exclude openjdk jdk/dynalink tests on openj9
  openjdk/excludes/ProblemList_openjdk16-openj9.txt
  openjdk/excludes/ProblemList_openjdk17-openj9.txt
Labels: bug

#2555 Exclude JCK17 targets that are known to fail due to infra issues
  jck/runtime.api/playlist.xml
Labels: bug
