Repository adoptium/aqa-tests, pull requests merged in 2021-05, with the labels that each got.

#2550 Update to testjob_template parameters' comments
  buildenv/jenkins/testJobTemplate
Labels: docs, enhancement

#2518 Update ProblemList_openjdk8.txt
  openjdk/excludes/ProblemList_openjdk8.txt
Labels: bug

#2559 Add GENERATE_JOBS parameter
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#2531 Added rerun.sh prorotype
  rerun.sh
Labels: enhancement

#2545 Updated "build.xml" to move download jtreg.jar logic in getDependencies
  openjdk/build.xml
Labels: enhancement

#2542 Replace references of openjdk-systemtest with aqa-systemtest
  README.md
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/testJobTemplate
  doc/RunAqa.md
  doc/Triage.md
  doc/userGuide.md
  external/README.md
  jck/README.md
  jck/build.xml
  jck/jck.mk
  jck/jck_target_folder_check/README.md
  jck/jck_target_folder_check/jck_target_folder_check.sh
  system/README.md
  system/common.xml
  system/jlm/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/modularity/playlist.xml
  system/otherLoadTest/playlist.xml
  system/sharedClasses/playlist.xml
  system/systemtest.mk
Labels: enhancement

#2581 Capture both out1 + out2 sections of junit report XML
  jck/xUnit.xsl
Labels: enhancement

#2417 Enable Dynamic agent
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/openjdk_tests
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#2598 Allow testsuite to be supplied as part of jck custom target
  jck/README.md
  jck/jck.mk
  jck/runtime.api/playlist.xml
Labels: enhancement
