Repository adoptium/aqa-tests, pull requests merged in 2021-02, with the labels that each got.

#2184 Stop using --strip on tar commands
  get.sh
Labels: bug

#2216 Allow users to set lightweight option
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#2229 Create ParallelStreamsLoadTest
  system/lambdaLoadTest/playlist.xml
Labels: enhancement

#2231 Remove _5m from ParallelStreamsLoadTest targets
  system/lambdaLoadTest/playlist.xml
Labels: bug

#2230 Enable java/lang/reflect/DefaultMethodMembers/FilterNotMostSpecific.java
  openjdk/ProblemList_openjdk11-openj9.txt
  openjdk/ProblemList_openjdk16-openj9.txt
  openjdk/ProblemList_openjdk17-openj9.txt
  openjdk/ProblemList_openjdk8-openj9.txt
Labels: bug

#2233 Move JdiTest playlist entry from lambdaLoadTest to otherLoadTest
  system/otherLoadTest/playlist.xml
Labels: bug

#2237 Replace deprecated triggers with new syntax
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#2239 Update userGuide to include vendor disable feature
  doc/userGuide.md
Labels: docs

#2234 Add a custom playlist target to run system tests
  buildenv/jenkins/JenkinsfileBase
  system/otherLoadTest/playlist.xml
  system/systemtest.mk
Labels: enhancement

#2242 OpenJ9 AArch64: Enable a BigInteger test back again
  openjdk/ProblemList_openjdk11-openj9.txt
Labels: bug

#2243 OpenJ9 AArch64: excluding stream/CountLargeTest
  openjdk/ProblemList_openjdk16-openj9.txt
  openjdk/ProblemList_openjdk17-openj9.txt
Labels: bug

#2249 Exclude com/sun/crypto AEAD ByteBuffer tests
  openjdk/ProblemList_openjdk16-openj9.txt
  openjdk/ProblemList_openjdk17-openj9.txt
Labels: exclude:temporary

#2244 Fix command injection vulnerability in autoTestPR
  .github/workflows/autoTestPR.yml
Labels: bug

#2259 Update the userGuide
  doc/userGuide.md
Labels: docs

#2241 Add certain directories trigger for PR/push testing
  .github/workflows/directoriesFilesChangePR.yml
  .github/workflows/getBuildLists.py
Labels: canosp_w21

#2251 Always set lightweight children
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#2267 Add jdk_vector for jdk16+
  openjdk/playlist.xml
Labels: enhancement

#2277 temporarily fix bug of get changed files
  .github/workflows/directoriesFilesChangePR.yml
Labels: bug, canosp_w21

#2283 add suffix to ignore native tests
  .github/workflows/directoriesFilesChangePR.yml
Labels: bug

#2285 Remove maketest.sh
  buildenv/jenkins/JenkinsfileBase
  doc/userGuide.md
  maketest.sh
Labels: enhancement

#2222 Add comment-triggered PR build action
  .github/workflows/runAqa.yml
  .github/workflows/runAqaArgParse.py
Labels: canosp_w21, discussion, enhancement

#2288 Update indentation for exclusion user guide
  doc/userGuide.md
Labels: enhancement

#2290 Prevent reportStatus job in runAqa.yml from running on every comment
  .github/workflows/runAqa.yml
Labels: bug

#2274 Set ulimit for sharedclasscache multithread tests
  system/sharedClasses/playlist.xml
Labels: bug

#2300 Add test excluded label for auto exclusion
  .github/workflows/autoTestPR.yml
Labels: enhancement

#2301 Change subset to version
  external/derby/playlist.xml
  external/elasticsearch/playlist.xml
  external/lucene-solr/playlist.xml
  external/openliberty-mp-tck/playlist.xml
  external/payara-mp-tck/playlist.xml
  external/quarkus_openshift/playlist.xml
  external/thorntail-mp-tck/playlist.xml
  external/tomee/playlist.xml
  jck/compiler.api/playlist.xml
  jck/compiler.lang/playlist.xml
  jck/devtools.java2schema/playlist.xml
  jck/devtools.jaxws/playlist.xml
  jck/devtools.schema2java/playlist.xml
  jck/devtools.schema_bind/playlist.xml
  jck/devtools.xml_schema/playlist.xml
  jck/runtime.api/playlist.xml
  jck/runtime.lang/playlist.xml
  jck/runtime.vm/playlist.xml
  openjdk/README.md
  openjdk/playlist.xml
  perf/dacapo/playlist.xml
  perf/idle_micro/playlist.xml
  system/jlm/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/modularity/playlist.xml
  system/otherLoadTest/playlist.xml
Labels: enhancement

#2304 Add alpine-linux and x86-64_solaris platforms
  buildenv/jenkins/openjdk_tests
Labels: enhancement
