Repository adoptium/aqa-tests, pull requests merged in 2021-01, with the labels that each got.

#2141 Perm exclude java/lang/StringBuilder/HugeCapacity.java
  openjdk/ProblemList_openjdk16-openj9.txt
Labels: test excluded, type:openjdk

#2139 Run chmod on .sh files under devtools directory only
  jck/build.xml
Labels: enhancement

#2146 Add mode150 and Mode650 in OpenJDK tests
  openjdk/playlist.xml
Labels: enhancement

#2134 Add Dynamic Breadth First Scan Ordering Testing
  system/daaLoadTest/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/otherLoadTest/playlist.xml
Labels: enhancement

#2148 Ensure the coverage for mixedref SDK in system tests
  system/daaLoadTest/playlist.xml
  system/jlm/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/modularity/playlist.xml
  system/otherLoadTest/playlist.xml
  system/sharedClasses/playlist.xml
Labels: enhancement

#2151 Add --add-opens java.base/java.lang=ALL-UNNAMED to MiniMix_5min for 11+
  system/otherLoadTest/playlist.xml
Labels: bug

#2147 Update test userGuilde for platform exclusion
  doc/userGuide.md
Labels: docs

#2167 Add Mode1000 into system tests
  system/jlm/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/modularity/playlist.xml
  system/otherLoadTest/playlist.xml
Labels: enhancement

#2164 Add Mode1000 in openjdk tests
  openjdk/playlist.xml
Labels: enhancement

#2168 Exclude sanity.openjdk java/lang/invoke tests
  openjdk/ProblemList_openjdk16-openj9.txt
Labels: exclude:temporary

#2179 Set failonerror to be true if build_image target fails
  external/build.xml
Labels: bug

#2176 Remove version number from system test prereq jar references in getDependency script
  buildenv/jenkins/getDependency
Labels: enhancement

#2188 Re-enable tests fixed by openj9#7119 and openj9#11699
  openjdk/ProblemList_openjdk16-openj9.txt
Labels: type:openjdk

#2201 Limit automatic triggered PR testing
  .github/workflows/PushOrPRtestbuild.yml
Labels: canosp_w21, enhancement

#2198 Consolidate openjdk tests for openj9 and hotspot
  openjdk/openjdk.mk
  openjdk/playlist.xml
Labels: enhancement

#2182 Add add-exports to HCRLateAttachWorkload_previewEnabled
  system/otherLoadTest/playlist.xml
Labels: bug

#2190 Add TRSS parser
  .gitignore
  doc/Triage.md
Labels: docs

#2118 Shorten test_output folder name to output
  .github/workflows/PushOrPRtestbuild.yml
  .github/workflows/actionExample.yml
  .gitignore
  buildenv/jenkins/JenkinsfileBase
  doc/userGuide.md
Labels: enhancement

#2203 Convert iteration based STF load test playlist targets to time-based
  system/daaLoadTest/playlist.xml
  system/lambdaLoadTest/playlist.xml
  system/mathLoadTest/playlist.xml
  system/mauveLoadTest/playlist.xml
  system/otherLoadTest/playlist.xml
Labels: enhancement
