Repository adoptium/aqa-tests, pull requests merged in 2021-06, with the labels that each got.

#2625 Set machine limit for dynamic vm to 100
  buildenv/jenkins/JenkinsfileBase
Labels: enhancement

#2583 Fix Curl download response validation for a Proxy environment
  get.sh
Labels: bug

#2630 Update github URLs
  README.md
  buildenv/jenkins/JenkinsfileBase
  buildenv/jenkins/openjdk_tests
  buildenv/jenkins/testJobTemplate
  external/README.md
  external/camel/README.md
  external/common_functions.sh
  external/elasticsearch/README.md
  external/elasticsearch/playlist.xml
  external/functional-test/dockerfile/Dockerfile
  external/jacoco/README.md
  external/jenkins/README.md
  external/kafka/README.md
  external/netty/README.md
  external/openliberty-mp-tck/playlist.xml
  external/payara-mp-tck/README.md
  external/payara-mp-tck/playlist.xml
  external/quarkus_openshift/README.md
  external/spring/README.md
  external/system-test/dockerfile/Dockerfile
  external/thorntail-mp-tck/README.md
  external/thorntail-mp-tck/playlist.xml
  external/tomee/README.md
  external/tomee/playlist.xml
  external/wildfly/README.md
  external/wycheproof/README.md
  openjdk/README.md
  openjdk/excludes/ProblemList_openjdk11-openj9.txt
  openjdk/excludes/ProblemList_openjdk11.txt
  openjdk/excludes/ProblemList_openjdk12-openj9.txt
  openjdk/excludes/ProblemList_openjdk12.txt
  openjdk/excludes/ProblemList_openjdk13-openj9.txt
  openjdk/excludes/ProblemList_openjdk13.txt
  openjdk/excludes/ProblemList_openjdk14-openj9.txt
  openjdk/excludes/ProblemList_openjdk14.txt
  openjdk/excludes/ProblemList_openjdk15-openj9.txt
  openjdk/excludes/ProblemList_openjdk15.txt
  openjdk/excludes/ProblemList_openjdk16-openj9.txt
  openjdk/excludes/ProblemList_openjdk16.txt
  openjdk/excludes/ProblemList_openjdk17-openj9.txt
  openjdk/excludes/ProblemList_openjdk17.txt
  openjdk/excludes/ProblemList_openjdk8-openj9.txt
  openjdk/excludes/ProblemList_openjdk8.txt
  openjdk/playlist.xml
  perf/README.md
  perf/dacapo/playlist.xml
  perf/renaissance/playlist.xml
Labels: enhancement

#2549 Added examples for specifying options for Grinder
  buildenv/jenkins/testJobTemplate
Labels: docs

#2634 Fix MBCS_Tests_i18n on zh_CN with JDK17
  functional/MBCS_Tests/datetime/src/FileTest.java
  functional/MBCS_Tests/i18n/src/DateFormatTest.java
  functional/MBCS_Tests/nio/src/UCompare.java
Labels: bug

#2612 openjdk-tests has been renamed to aqa-tests
  get.sh
Labels: enhancement

#2644 Initial addition of Contributing.md file
  Contributing.md
Labels: enhancement

#2579 Update <plat> to <platform> for disabled element
  doc/userGuide.md
  jck/compiler.api/playlist.xml
  jck/compiler.lang/playlist.xml
  jck/devtools.java2schema/playlist.xml
  jck/devtools.jaxws/playlist.xml
  jck/devtools.schema2java/playlist.xml
  jck/devtools.schema_bind/playlist.xml
  jck/devtools.xml_schema/playlist.xml
  jck/runtime.api/playlist.xml
  jck/runtime.xml_schema/playlist.xml
  openjdk/playlist.xml
  perf/renaissance/playlist.xml
  system/lambdaLoadTest/playlist.xml
Labels: enhancement

#2641 Exclude compiler/gcbarriers/UnsafeIntrinsicsTest.java jdk11 aarch64
  openjdk/excludes/ProblemList_openjdk11.txt
Labels: bug

#2649 Add CPU and Memory detection for Solaris
  openjdk/openjdk.mk
Labels: enhancement

#2639 Exclude some jdk_management tests jdk8 jdk11 hotspot
  openjdk/excludes/ProblemList_openjdk11.txt
  openjdk/excludes/ProblemList_openjdk8.txt
Labels: bug

#2653 Switching OpenJDK Test src to use adoptium mirrors
  openjdk/build.xml
Labels: bug

#2648 Excluding tools/launcher test on OpenJ9
  openjdk/excludes/ProblemList_openjdk11-openj9.txt
Labels: bug

#2530 Set Jenkins node temporarily offline due to specific machine issue
  buildenv/jenkins/openjdk_tests
  buildenv/jenkins/testJobTemplate
Labels: enhancement

#2689 Fix JCK update logic
  jck/build.xml
Labels: bug
